# Generated by Django 4.2.6 on 2023-10-23 11:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserIncome',
            new_name='Income',
        ),
    ]
